#!/usr/bin/python3

# Script:                   401 Ops Challenge Day 44
# Author:                   Mario Pugh
# Date of latest revision:  12/7/20
# Purpose:                  Create a Port Scanner
import socket

sockmod = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
timeout = # TODO: Set a timeout value here.
sockmod.settimeout(timeout)

hostip = # TODO: Collect a host IP from the user.
portno = # TODO: Collect a port number from the user, then convert it to an integer data type.

def portScanner(portno):
    if sockmod.FUNCTION((hostip, portno)): # TODO: Replace "FUNCTION" with the appropriate socket.function call as found in the [socket docs](https://docs.python.org/3/library/socket.html)
        print("Port closed")
    else:
        print("Port open")

portScanner(port)
