#!/usr/bin/env python3
# Script:                   401 Op Challenge Day 31
# Author:                   Mario Pugh
# Date of latest revision:  11/16/20
# Purpose:                  Signature-based Malware Detection Part (1 of 3)

# Import libraries

import os
import time

# Declaration of variables

print("""\

                                        .;;!!!@!!!;.
.!!!!!;.                             .;!!!!!!!!!!!!!
----!!!!!!.                       .;!!!!!!!!!!UWWW$$$   
    :$$NWX!!:                  .:!!!!!!XUWW$$$$$$$$$P
    $$$$$##WX!;            :<!!!!UW$$$$$"  $$$$$$$$#
    $$$$$  $$$UX         :!!UW$$$$$$$$$$   4$$$$$*
    ^$$$B  $$$$\           $$$$$$$$$$$$$   d$$R"
      "*$bd$$$$            '*$$$$$$$$$$$$o+#"
           ''''                '''''''''
                                         xxxxx
 xxxxxx                                xxx   
     xx                              xxx
      xx                            xxx
       xx                         xxx  
         xx                    xxx    
            xxxxxxxxxxxxxxxxx x 
                xxxxxxxxx
                  xxxxx

    """)


# Declaration of function

# Linux search
def malwareSearcherLinux():
    targetFile = input("State the name of your target file  ")
    dir = input("Enter the directory to search  ")
    os.system("ls " + str(dir) + " | echo \"Searched $(wc -l) files.\"")
    os.system("find " + str(dir) + ' -name ' + str(targetFile) + " -print | echo \"Found $(grep -c /) files that matched:\"")
    print("")
    os.system("find " + str(dir) + ' -name ' + str(targetFile))
    print("")

# Main

malwareSearcherLinux()

# End
