#!/usr/bin/env python3

# Script Name: uptimeSensor.py
# Author: Mario Pugh
# Date of last revision: October 6, 2020
# Description of purpose: Create an uptime sensor to evaluate host LAN up or down. 

import os, time

# Declaration of functions
# Transmit a single ICMP (ping) packet to a specific IP every two seconds.
# Evaluate the response as either success or failure.
# Assign success or failure to a status variable.
# For every ICMP transmission attempted, print the status variable along with a comprehensive timestamp and destination IP tested.
# Example output: 2020-10-05 17:57:57.510261 Network Active to 8.8.8.8

# Main

while True:
    ip = "127.0.0.1"
    response = os.system(f"ping {ip}")
    if 0 == response:
        print(f"UP {ip} Ping was Successful")
    else:
        print(f"DOWN {ip} Ping was Unsuccessful")
    time.sleep(2)

# End
