#!/usr/bin/python3

# Script:                   401 Ops Challenge Day 44
# Author:                   Mario Pugh
# Date of latest revision:  12/7/20
# Purpose:                  Create a Port Scanner
import socket

sockmod = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
timeout = 3000
sockmod.settimeout(timeout)

hostip = input("What IP address? ")
portno = input("What port? ")

def portScanner(portno):
# TODO: Replace "FUNCTION" with the appropriate socket.function call as found in the [socket docs](https://docs.python.org/3/library/socket.html)
    if sockmod.bind((hostip, int(portno))): 
        print("Port closed")
    else:
        print("Port open")

portScanner(port)
