#!/usr/bin/env python3

# Script Name: uptimeSensor.py
# Author: Mario Pugh
# Date of last revision: November 10, 2020
# Description of purpose: Create an uptime sensor to evaluate host LAN up or down. 

import logging, time, os
from logging.handlers import RotatingFileHandler

import os, time, datetime;
# Declaration of functions
def sendingPings(target):
# Transmit a single ICMP (ping) packet to a specific IP every two seconds.
    response = os.system("ping -c 1 " + target)
# Evaluate the response as either success or failure.
# Assign success or failure to a status variable.
    if response == 0:
        sentPing = "Network Active"
    else:
        sentPing = "Network Error"
    return pingstatus
sentPing = sendingPings("127.0.0.1")
# For every ICMP transmission attempted, print the status variable along with a comprehensive timestamp and destination IP tested every 3 seconds.
# Main
# Example output: 2020-10-05 17:57:57.510261 Network Active to 127.0.0.1
while True:
    now = datetime.datetime.now()
    print(str(now) + " " + sentPing + " to 127.0.0.1")
    time.sleep(3)
    
logging.basicConfig(filename='error_log.txt', level=logging.WARNING)
print('Logging started')
logging.debug('Debug Information')
logging.info('info Information')
logging.warning('warning Information')
logging.error('error Information')
logging.critical('critical Information')
print('Logging end')

logger = logging.getLogger('my_logger')
handler = RotatingFileHandler('my_log.log', maxBytes=VALUE, backupCount=VALUE) #set each VALUE
logger.addHandler(handler)

for i in range(VALUE): #set each VALUE
    logmsg = "Doing it LIVE!"
    logmsg += str(i)
    logger.warning(logmsg)
    print ("Doing it LIVE! number", i)
    os.system("ls -al")
    time.sleep(.1)
    
# End
