#!/usr/bin/env python3

# Script Name: uptimeSensorP2.py
# Author: Mario Pugh
# Date of last revision: October 7, 2020
# Description of purpose: Create an uptime sensor to evaluate host LAN up or down. 

import os, time
import pythonping
import smtplib
from pythonping import ping
from email.message import EmailMessage

# Declaration of variables

# Do not hardcode the password, have user input it.
user_password = input("Please enter your email password for testing: ")

# Declaration of functions

# Send an email to the administrator if a host status changes from “up” to “down”.
# The email message should clearly indicate which host status changed, the status before and after, and a timestamp of the event.
# Send an email to the administrator if a host status changes from “down” to “up”.
# The email message should clearly indicate which host status changed, the status before and after, and a timestamp of the event.

while(1):
    try:
        ip="8.8.8.8"

        # Creates an SMTP session
        s = smtplib.SMTP_SSL("smtp.gmail.com", 465)

        # Start TLS for security
        s.ehlo()

        # Authentication
        s.login("opstester401@gmail.com", user_password)

        # Instance of email message
        msg = EmailMessage()

        # Write the subject
        msg["Subject"]= " The pings are comings..."
        msg["From"]="opstester401@gmail.com"
        msg["To"]="opstester401@gmail.com"
        response = os.system(f"ping -c 1 " +ip)
        if 0 == response:
            text=f"{time.ctime()} UP {ip} Ping was Successful"
        else:
            text=f"{time.ctime()} DOWN {ip} Ping was Unsuccessful"

        # Attach the content with the msg instance
        msg.set_content(text)

        # Sending the mail
        s.send_message(msg)
        s.quit()
        print('sent')
        time.sleep(2)
    except:
        print('site is down yet...')
        print('sleeping...')

        # Sleeping for 10 seconds
        time.sleep(10)
        print('Trying again')

# Main

# End

# $$$$$$$$$$$$$$$$$$$$$$$$$$$**""""`` ````"""#*R$$$$$$$$$$$$$$$$$$$$$$$$$$$
# $$$$$$$$$$$$$$$$$$$$$$*""      ..........      `"#$$$$$$$$$$$$$$$$$$$$$$$
# $$$$$$$$$$$$$$$$$$$#"    .ue@$$$********$$$$Weu.   `"*$$$$$$$$$$$$$$$$$$$
# $$$$$$$$$$$$$$$$#"   ue$$*#""              `""*$$No.   "R$$$$$$$$$$$$$$$$
# $$$$$$$$$$$$$P"   u@$*"`                         "#$$o.  ^*$$$$$$$$$$$$$$
# $$$$$$$$$$$P"  .o$R"               . .WN.           "#$Nu  `#$$$$$$$$$$$$
# $$$$$$$$$$"  .@$#`       'ou  .oeW$$$$$$$$W            "$$u  "$$$$$$$$$$$
# $$$$$$$$#   o$#`      ueL  $$$$$$$$$$$$$$$$ku.           "$$u  "$$$$$$$$$
# $$$$$$$"  x$P`        `"$$u$$$$$$$$$$$$$$"#$$$L            "$o   *$$$$$$$
# $$$$$$"  d$"        #$u.2$$$$$$$$$$$$$$$$  #$$$Nu            $$.  #$$$$$$
# $$$$$"  @$"          $$$$$$$$$$$$$$$$$$$$k  $$#*$$u           #$L  #$$$$$
# $$$$"  d$         #Nu@$$$$$$$$$$$$$$$$$$"  x$$L #$$$o.         #$c  #$$$$
# $$$F  d$          .$$$$$$$$$$$$$$$$$$$$N  d$$$$  "$$$$$u        #$L  #$$$
# $$$  :$F        ..`$$$$$$$$$$$$$$$$$$$$$$$$$$$`    R$$$$$eu.     $$   $$$
# $$!  $$        . R$$$$$$$$$$$$$$$$$$$$$$$$$$$$$.   @$$$$$$$$Nu   '$N  `$$
# $$  x$"        Re$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$uu@"``"$$$$$$$i   #$:  $$
# $E  $$       c 8$$$$$$$$$$$$$$$$$$$$$G(   ``^*$$$$$$$WW$$$$$$$$N   $$  4$
# $~ :$$N. tL i)$$$$$$$$$$$$$$$$$$$$$$$$$N       ^#R$$$$$$$$$$$$$$$  9$  '$
# $  t$$$$u$$W$$$$$$$$$$$$$$!$$$$$$$$$$$$$&       . c?"*$$$R$$$$$$$  '$k  $
# $  @$$$$$$$$$$$$$$$$$$$$"E F!$$$$$$$$$$."        +."@\* x .""*$$"   $B  $
# $  $$$$$$$$$$$$$$$$"$)#F     $$$$$$$$$$$           `  -d>x"*=."`    $$  $
# $  $$$$$$$$$$?$$R'$ `#d$""    #$$$$$$$$$ > .                "       $$  $
# $  $$$$$$$($$@$"` P *@$.@#"!    "*$$$$$$$L!.                        $$  $
# $  9$$$$$$$L#$L  ! " <$$`          "*$$$$$NL:"z  f                  $E  $
# $> ?$$$$ $$$b$^      .$c .ueu.        `"$$$$b"x"#  "               x$!  $
# $k  $$$$N$ "$$L:$oud$$$` d$ .u.         "$$$$$o." #f.              $$   $
# $$  R$""$$o.$"$$$$""" ue$$$P"`"c          "$$$$$$Wo'              :$F  t$
# $$: '$&  $*$$u$$$$u.ud$R" `    ^            "#*****               @$   $$
# $$N  #$: E 3$$$$$$$$$"                                           d$"  x$$
# $$$k  $$   F *$$$$*"                                            :$P   $$$
# $$$$  '$b                                                      .$P   $$$$
# $$$$b  `$b                                                    .$$   @$$$$
# $$$$$N  "$N                                                  .$P   @$$$$$
# $$$$$$N  '*$c                                               u$#  .$$$$$$$
# $$$$$$$$.  "$N.                                           .@$"  x$$$$$$$$
# $$$$$$$$$o   #$N.                                       .@$#  .@$$$$$$$$$
# $$$$$$$$$$$u  `#$Nu                                   u@$#   u$$$$$$$$$$$
# $$$$$$$$$$$$$u   "R$o.                             ue$R"   u$$$$$$$$$$$$$
# $$$$$$$$$$$$$$$o.  ^#$$bu.                     .uW$P"`  .u$$$$$$$$$$$$$$$
# $$$$$$$$$$$$$$$$$$u   `"#R$$Wou..... ....uueW$$*#"   .u@$$$$$$$$$$$$$$$$$
# $$$$$$$$$$$$$$$$$$$$Nu.    `""#***$$$$$***"""`    .o$$$$$$$$$$$$$$$$$$$$$
# $$$$$$$$$$$$$$$$$$$$$$$$$eu..               ...ed$$$$$$$$$$$$$$$$$$$$$$$$
# $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$NWWeeeeedW@$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
# $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
